@api= http://127.0.0.1:50901/cfop
# @api= http://dev.mofunc.com/cfop
@accessToken= cH6ZaK5ufS7tV

### f2ls ++++++

### create
POST {{api}}/f2ls
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

{
	"number": 21,
	"image":"no-image",
	"formula":"RUR'U'",
	"tags":[{
		"type": "primary",
		"_id": "5bcc2e821a6f5c5f7a6b8eaa",
		"label": "21",
		"updatedAt": "2018-10-21T07:45:06.487Z",
		"createdAt": "2018-10-21T07:45:06.487Z",
		"__v": 0
		}]
}

### query f2ls
GET {{api}}/f2ls
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

### get a f2l
GET {{api}}/f2ls/5bc20639a612ec187856e111
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

### update a f2l
PATCH  {{api}}/f2ls/5bcc2eed1a6f5c5f7a6b8eac
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

{
	"order": 30,
	"tags":[]
}

### delete a f2l
DELETE  {{api}}/f2ls/5b8e55111cb0e6125a9c0311
Content-Type: application/json
x-serve: service

### f2ls ------
