@api= http://127.0.0.1:50901/services
# @api= http://dev.mofunc.com/services
@accessToken= cH6ZaK5ufS7tV

### login
POST {{api}}/access-tokens
Content-Type: application/json
x-serve: service

{
	"login": "admin",
	"password": "123456",
	"client":"test"
}

### check token
GET {{api}}/access-tokens
Content-Type: application/json
x-serve: service

#### get my profile
GET {{api}}/me
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

#### notes
POST  {{api}}/accesses
Content-Type: application/json
x-serve: service

{
	"resource": "/",
	"ip": "127.0.0.1",
	"action": "get",
	"client":"mofunc.com",
	"host":"mongo.mofunc.com",
	"referer":"dev.mofunc.com"
}

#### get accesses
GET {{api}}/accesses
Content-Type: application/json
x-serve: service

### users ++++++

### create
POST {{api}}/users
Content-Type: application/json
x-serve: service

{
	"username": "username",
	"password": "password",
	"client":"client",
	"email":"email@email",
	"phone":"13456789012"
}

### query users
GET {{api}}/users
Content-Type: application/json
x-serve: service

### get a user
GET {{api}}/users/5b8e55871cb0e6125a9c0314
Content-Type: application/json
x-serve: service

### update a user
PATCH  {{api}}/users/5b8e55871cb0e6125a9c0314
Content-Type: application/json
x-serve: service

{
	"client": "client"
}

### delete a user
DELETE  {{api}}/users/5b8e55111cb0e6125a9c0311
Content-Type: application/json
x-serve: service

### users ------


### packages ++++++

### create
POST {{api}}/packages
Content-Type: application/json
x-serve: service

{
	"username": "username",
	"password": "password",
	"client":"client",
	"email":"email@email",
	"phone":"13456789012"
}

### query packages
GET {{api}}/packages
Content-Type: application/json
x-serve: service

### get a package
GET {{api}}/packages/5b8e55871cb0e6125a9c0314
Content-Type: application/json
x-serve: service

### update a package
PATCH  {{api}}/packages/5b8e55871cb0e6125a9c0314
Content-Type: application/json
x-serve: service

{
	"client": "client"
}

### delete a package
DELETE  {{api}}/packages/5b8e55111cb0e6125a9c0311
Content-Type: application/json
x-serve: service

### packages ------


### squats ++++++

### create
POST {{api}}/squats
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

{
	"count": 10,
	"referenceDate":"2018-09-30"
}

### query squats
GET {{api}}/squats
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

### get a squat
GET {{api}}/squats/5bc20639a612ec187856e111
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

### update a squat
PATCH  {{api}}/squats/5b8e55871cb0e6125a9c0314
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

{
	"count": 30
}

### delete a squat
DELETE  {{api}}/squats/5b8e55111cb0e6125a9c0311
Content-Type: application/json
x-serve: service

### squats ------

### aggregation ++++++

### get aggregation
GET {{api}}/aggregation
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

### git aggregation
GET {{api}}/aggregation/git/lglong519
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

### aggregation ------

### test
GET {{api}}/test
Content-Type: application/json
x-serve: service