@api= http://127.0.0.1:50901/tieba
# @api= http://dev.mofunc.com/tieba
@accessToken= cH6ZaK5ufS7tV

### tieba-accounts ++++++

### create
POST {{api}}/tieba-accounts
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

{
	"BDUSS":"BDUSS"
}

### query tieba-accounts
GET {{api}}/tieba-accounts
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

### query tieba-accounts users
GET {{api}}/tieba-accounts/users
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

### get a tieba-account
GET {{api}}/tieba-accounts/5bc20639a612ec187856e111
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

### update a tieba-account
PATCH  {{api}}/tieba-accounts/5beec817eed780512e483146
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

{
	"BDUSS": "V0WFJiQVdkVVo3ZDN"
}

### delete a tieba-account
DELETE  {{api}}/tieba-accounts/5b8e55111cb0e6125a9c0311
Content-Type: application/json
x-serve: service


### sign a tieba-account
POST {{api}}/tieba-accounts/5beec817eed780512e483146/sign
Content-Type: application/json
x-serve: service

### summarize a tieba-account
GET {{api}}/tieba-accounts/5beec817eed780512e483146/summarize
Content-Type: application/json
x-serve: service
### tieba-accounts ------

### sync
POST {{api}}/tieba-accounts/5bef2cd9eed780512e489ce4/tiebas/sync
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

### create a tieba
POST {{api}}/tiebas
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

{
	"tiebaAccount": "5c26ee2aedadca58a1c37d68",
    "user": "5c26ebc8edadca58a1c37d4b",
	"kw":"魔方"
}

### get tiebas
GET {{api}}/tiebas
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}

### sign one
POST {{api}}/tiebas/5beec821eed780512e483182/sign
Content-Type: application/json
x-serve: service
x-access-token: {{accessToken}}
